version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: example
  app:
    image: myapp:latest
    ports:
      - "8080:8080"
